
module CharacterData

  def characters
    [
      "The Butcher",
      "Li-Ming",
      "Valla",
      "Azmodan",
      "Nazeebo",
      "Xul",
      "Khara,zim",
      "Diablo",
      "Johanna",
      "Leoric",
      "Sonya",
      "Tyrael",
      "Kerrigan",
      "Nova",
      "Raynor",
      "Tychus",
      "Zeratul",
      "Abathur",
      "Sgt. Hammer",
      "Zagara",
      "Lt. Morales",
      "Tassadar",
      "Artanis",
      "Dehaka",
      "Chromie",
      "Falstad",
      "Gall (Cho'gall)",
      "Gul'dan",
      "Greymane",
      "Illidan",
      "Jaina",
      "Kael'thas",
      "Lunara",
      "Thrall",
      "Gazlowe",
      "Medivh",
      "Murky",
      "Sylvanas",
      "Brightwing",
      "Li Li",
      "Malfurion",
      "Rehgar",
      "Tyrande",
      "Uther",
      "Anub'arak",
      "Arthas",
      "Chen",
      "Cho (Cho'gall)",
      "Elite Tauren Chieftain",
      "Muradin",
      "Rexxar",
      "Stitches",
    ]
  end

  def maps
    [
      "Tomb of the Spider Queen",
      "Sky Temple",
      "Towers of Doom",
      "Blackheart's Bay",
      "Cursed Hollows",
      "Infernal Shrines",
      "Battlefeild of Eternity",
      "Garden of Terror",
      "Dragon Shire",
      "Haunted Mines"
    ]
  end
end
